--- 
services: 
  app: 
    build: 
      context: ./
      dockerfile: app.dockerfile
    ports: 
      - "8081:80"
    restart: always
  database: 
    environment: 
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_USERNAME: root
      MYSQL_USER: "${DB_USERNAME}"
    image: "mysql:5.6"
    ports: 
      - "33061:3306"
version: "3"
